/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import VegasEVM.Contract.ClassicalEVMStorage
import VegasEVM.Contract.Imperative

/-!
# Classical EVM handler inventory

This pass routes every graph node to the deterministic classical ABI and
lowers its readiness requirements to the certified total EVM storage layout.
Commit and reveal nodes have one route; a sample node has a request route and
a callback route because classical chance is a two-transaction protocol.

The resulting IR still retains typed node code for expression-specific
lowering. Its structural checks, however, are already concrete EVM storage
reads, and acceptance over an encoded snapshot is proved exactly equivalent to
event-graph readiness.
-/

namespace Vegas.Machine.Contract.EVM

open EventGraph

noncomputable section

variable {Player : Type} [DecidableEq Player]
variable {L : IExpr} {program : Program Player L}

/-- Deterministic classical entry point responsible for one node operation. -/
inductive ClassicalRoute where
  | player
  | reveal
  | sampleRequest
  | oracleCallback
deriving DecidableEq

/-- Entry-point routes generated by one node's semantic kind. -/
def classicalRoutes : NodeSem Player L → List ClassicalRoute
  | .commit _ _ => [.player]
  | .reveal _ => [.reveal]
  | .sample _ => [.sampleRequest, .oracleCallback]

/-- One completion-bit assertion in the total EVM layout. -/
structure ClassicalStorageCheck where
  slot : Nat
  expected : Bool
deriving DecidableEq

namespace ClassicalStorageCheck

/-- Evaluate a storage assertion, rejecting noncanonical Boolean words. -/
def evaluate (storage : TotalStorage) (check : ClassicalStorageCheck) : Bool :=
  match decodeBool (storage check.slot) with
  | none => false
  | some actual => decide (actual = check.expected)

end ClassicalStorageCheck

/-- Lower one logical readiness requirement to its total EVM completion cell.
-/
def lowerClassicalRequirement
    (requirement : Imperative.Requirement program) : ClassicalStorageCheck :=
  let layout := ClassicalStorageLayout.canonical program
  match requirement with
  | .notCompleted node =>
      { slot := layout.address (.completed node), expected := false }
  | .completed node =>
      { slot := layout.address (.completed node), expected := true }

/-- Concrete ordered EVM checks for one graph node. Replay prevention remains
first, followed by prerequisites in canonical `Finset.toList` order. -/
def classicalChecks (program : Program Player L)
    (node : Fin program.graph.nodeCount) : List ClassicalStorageCheck :=
  (Imperative.requirements program node).map lowerClassicalRequirement

/-- Lowering one readiness requirement to total EVM storage preserves its
semantic truth value. -/
theorem lowerClassicalRequirement_correct
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (requirement : Imperative.Requirement program) :
    ClassicalStorageCheck.evaluate
        (encodeClassicalSnapshot codec words nodes
          { graph := StateSnapshot.ofConfig cfg, pending := pending })
        (lowerClassicalRequirement requirement) =
      Imperative.Requirement.evaluate cfg requirement := by
  cases requirement with
  | notCompleted node =>
      unfold ClassicalStorageCheck.evaluate lowerClassicalRequirement
      dsimp only
      rw [encodeClassicalSnapshot_completed, decodeBool_encodeBool]
      simp only [StateSnapshot.ofConfig_done, Imperative.Requirement.evaluate,
        decide_not]
      exact Bool.decide_eq_false
  | completed node =>
      unfold ClassicalStorageCheck.evaluate lowerClassicalRequirement
      dsimp only
      rw [encodeClassicalSnapshot_completed, decodeBool_encodeBool]
      simp only [StateSnapshot.ofConfig_done, Imperative.Requirement.evaluate]
      exact Bool.decide_eq_true

/-- A true logical requirement is stored as exactly its expected canonical
Boolean word after lowering. -/
theorem lowerClassicalRequirement_storage_eq_of_true
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (requirement : Imperative.Requirement program)
    (htrue : Imperative.Requirement.evaluate cfg requirement = true) :
      encodeClassicalSnapshot codec words nodes
        { graph := StateSnapshot.ofConfig cfg, pending := pending }
        (lowerClassicalRequirement requirement).slot =
      encodeBool (lowerClassicalRequirement requirement).expected := by
  cases requirement with
  | notCompleted node =>
      have hnotDone : node ∉ cfg.done := by
        simpa [Imperative.Requirement.evaluate] using htrue
      change
        encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending }
            ((ClassicalStorageLayout.canonical program).address
              (.completed node)) =
          encodeBool false
      rw [encodeClassicalSnapshot_completed]
      simp [hnotDone]
  | completed node =>
      have hdone : node ∈ cfg.done := by
        simpa [Imperative.Requirement.evaluate] using htrue
      change
        encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending }
            ((ClassicalStorageLayout.canonical program).address
              (.completed node)) =
          encodeBool true
      rw [encodeClassicalSnapshot_completed]
      simp [hdone]

/-- Ordered concrete EVM completion checks accept exactly ready source nodes.
-/
theorem classicalChecks_accept_iff_ready
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (node : Fin program.graph.nodeCount) :
    Imperative.evaluateAll
        (ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending }))
        (classicalChecks program node) =
      decide (Ready program.graph cfg node) := by
  unfold classicalChecks
  unfold Imperative.evaluateAll
  rw [List.all_map]
  have hevaluate :
      (fun requirement =>
        ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending })
          (lowerClassicalRequirement requirement)) =
        Imperative.Requirement.evaluate cfg := by
    funext requirement
    exact lowerClassicalRequirement_correct codec words nodes cfg pending
      requirement
  change (Imperative.requirements program node).all
      (fun requirement =>
        ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending })
          (lowerClassicalRequirement requirement)) = _
  rw [hevaluate]
  exact Imperative.evaluateAll_requirements cfg node

/-- Source readiness supplies the exact canonical word expected by every
generated EVM storage check. -/
theorem classicalChecks_storage_eq_of_ready
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (node : Fin program.graph.nodeCount)
    (ready : Ready program.graph cfg node)
    (check : ClassicalStorageCheck)
    (hcheck : check ∈ classicalChecks program node) :
    encodeClassicalSnapshot codec words nodes
        { graph := StateSnapshot.ofConfig cfg, pending := pending }
        check.slot = encodeBool check.expected := by
  unfold classicalChecks at hcheck
  rcases List.mem_map.mp hcheck with ⟨requirement, hrequirement, rfl⟩
  apply lowerClassicalRequirement_storage_eq_of_true
  cases requirement with
  | notCompleted checked =>
      simp only [Imperative.requirements, List.mem_cons,
        Imperative.Requirement.notCompleted.injEq, List.mem_map,
        Finset.mem_toList, reduceCtorEq, and_false, exists_false, or_false]
        at hrequirement
      subst checked
      simp [Imperative.Requirement.evaluate, ready.1]
  | completed checked =>
      simp only [Imperative.requirements, List.mem_cons, reduceCtorEq,
        List.mem_map, Finset.mem_toList,
        Imperative.Requirement.completed.injEq, exists_eq_right, false_or]
        at hrequirement
      exact by
        simp [Imperative.Requirement.evaluate, ready.2 hrequirement]

/-- Every storage key read by generated readiness checks is represented
exactly under the backend layout-capacity certificate. -/
theorem classicalChecks_slot_lt_word
    (fits : ClassicalStorageFitsWord program)
    (node : Fin program.graph.nodeCount)
    (check : ClassicalStorageCheck)
    (hcheck : check ∈ classicalChecks program node) :
    check.slot < 2 ^ 256 := by
  unfold classicalChecks at hcheck
  rcases List.mem_map.mp hcheck with ⟨requirement, _hrequirement, rfl⟩
  cases requirement with
  | notCompleted checked | completed checked =>
      exact classicalStorageAddress_lt_word fits (.completed checked)

/-- One routed node plan for handler-specific lowering. -/
structure ClassicalActionIR (program : Program Player L) where
  node : Fin program.graph.nodeCount
  route : ClassicalRoute
  routed : route ∈ classicalRoutes (program.graph.nodeRow node).sem
  checks : List ClassicalStorageCheck
  valueSlot : Nat
  presenceSlot : Nat
  completionSlot : Nat
  checks_eq : checks = classicalChecks program node
  valueSlot_eq : valueSlot =
    (ClassicalStorageLayout.canonical program).address
      (.fieldValue
        ⟨program.graph.nodeTarget node,
          StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
  presenceSlot_eq : presenceSlot =
    (ClassicalStorageLayout.canonical program).address
      (.fieldPresent
        ⟨program.graph.nodeTarget node,
          StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
  completionSlot_eq : completionSlot =
    (ClassicalStorageLayout.canonical program).address (.completed node)

namespace ClassicalActionIR

/-- Every generated value slot is exactly representable by an EVM storage
key under the backend layout bound. -/
theorem valueSlot_lt_word (fits : ClassicalStorageFitsWord program)
    (action : ClassicalActionIR program) :
    action.valueSlot < 2 ^ 256 := by
  rw [action.valueSlot_eq]
  exact classicalStorageAddress_lt_word fits _

/-- Every generated presence slot is exactly representable by an EVM storage
key under the backend layout bound. -/
theorem presenceSlot_lt_word (fits : ClassicalStorageFitsWord program)
    (action : ClassicalActionIR program) :
    action.presenceSlot < 2 ^ 256 := by
  rw [action.presenceSlot_eq]
  exact classicalStorageAddress_lt_word fits _

/-- Every generated completion slot is exactly representable by an EVM
storage key under the backend layout bound. -/
theorem completionSlot_lt_word (fits : ClassicalStorageFitsWord program)
    (action : ClassicalActionIR program) :
    action.completionSlot < 2 ^ 256 := by
  rw [action.completionSlot_eq]
  exact classicalStorageAddress_lt_word fits _

end ClassicalActionIR

/-- Compile one graph node into all deterministic routes that implement it. -/
def compileClassicalActions (program : Program Player L)
    (node : Fin program.graph.nodeCount) : List (ClassicalActionIR program) :=
  let layout := ClassicalStorageLayout.canonical program
  (classicalRoutes (program.graph.nodeRow node).sem).attach.map fun route =>
    { node := node
      route := route.1
      routed := route.2
      checks := classicalChecks program node
      valueSlot := layout.address
        (.fieldValue
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      presenceSlot := layout.address
        (.fieldPresent
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      completionSlot := layout.address (.completed node)
      checks_eq := rfl
      valueSlot_eq := rfl
      presenceSlot_eq := rfl
      completionSlot_eq := rfl }

/-- Complete classical EVM handler inventory. -/
structure ClassicalContractIR (program : Program Player L) where
  storageSize : Nat
  actions : List (ClassicalActionIR program)

/-- Compile every graph node in stable order to its classical handler routes.
-/
def compileClassicalIR (program : Program Player L) :
    ClassicalContractIR program where
  storageSize := (ClassicalStorageLayout.canonical program).slotCount
  actions := program.graph.nodeOrder.flatMap (compileClassicalActions program)

/-- Every generated action retains exactly the concrete checks of its node. -/
@[simp] theorem compileClassicalActions_checks
    (node : Fin program.graph.nodeCount)
    (action : ClassicalActionIR program)
    (_hmem : action ∈ compileClassicalActions program node) :
    action.checks = classicalChecks program action.node := by
  exact action.checks_eq

/-- Every commit node has its player handler plan. -/
theorem player_action_mem_of_commit
    (node : Fin program.graph.nodeCount) (who : Player) (guard : EventGuard L)
    (hsem : (program.graph.nodeRow node).sem = .commit who guard) :
    ∃ action ∈ (compileClassicalIR program).actions,
      action.node = node ∧ action.route = .player := by
  let action : ClassicalActionIR program :=
    { node := node
      route := .player
      routed := by simp [hsem, classicalRoutes]
      checks := classicalChecks program node
      valueSlot := (ClassicalStorageLayout.canonical program).address
        (.fieldValue
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      presenceSlot := (ClassicalStorageLayout.canonical program).address
        (.fieldPresent
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      completionSlot := (ClassicalStorageLayout.canonical program).address
        (.completed node)
      checks_eq := rfl
      valueSlot_eq := rfl
      presenceSlot_eq := rfl
      completionSlot_eq := rfl }
  refine ⟨action, ?_, rfl, rfl⟩
  simp [compileClassicalIR, compileClassicalActions, Graph.mem_nodeOrder,
    action, hsem, classicalRoutes]

/-- The three cells written by a successful routed action are pairwise
distinct. -/
theorem ClassicalActionIR.writeSlots_pairwise
    (action : ClassicalActionIR program) :
    action.valueSlot ≠ action.presenceSlot ∧
      action.valueSlot ≠ action.completionSlot ∧
      action.presenceSlot ≠ action.completionSlot := by
  rw [action.valueSlot_eq, action.presenceSlot_eq, action.completionSlot_eq]
  have injective := (ClassicalStorageLayout.canonical program).injective
  constructor
  · intro heq
    have := injective heq
    cases this
  · constructor
    · intro heq
      have := injective heq
      cases this
    · intro heq
      have := injective heq
      cases this

end

end Vegas.Machine.Contract.EVM
