/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Compile.ApplicationPlan
import Vegas.Compile.BindingImageController
import Vegas.Compile.ApplicationImageController
import Vegas.Compile.ConditionalImageController

/-! # Source-profile lifting for generated applications

An application derivation mathematically lifts a source behavioral profile to
reference runtime policies. Dispatch follows the first unresolved source
instruction, using public completion flags. It waits for another owner's
instruction, pending inclusion, or chance rather than executing a later source
decision early.

This is a proof-level strategy lifting, not generated player software and not a
restriction on raw runtime strategies or deviations. Environment services
still choose delivery, inclusion, clocks, and chance invocations. The lifted
policy receives only its own command history and native observation; source
environments are absent. The supplied image is the complete application,
shared by recursive suffixes.
-/

noncomputable section

namespace Vegas.ApplicationPlan

open EventGraph ToEventGraph Interaction Interaction.MessageApplication
  GameTheory.Math.Probability

variable {P : Type} [DecidableEq P] {L : IExpr}

/-- Internal source-profile lifting in an ambient full image.
The image is held fixed through recursion so suffix policies invoke the same
application, not a fresh suffix runtime. Normal clients should use `liftProfile`,
which supplies the image generated by the complete plan. -/
def liftProfileIn (image : ApplicationImage P L) (deadlineOf : Nat → Nat) :
    {Γ : VCtx P L} → {pending : Finset VarId} → {prog : VegasCore P L Γ} →
      {accounted : CommitmentAccounting pending prog} → {fresh : FreshBindings prog} →
      {state : BuildState P L Γ} → ApplicationPlan accounted fresh state →
        SourceBehavioralProfile prog → P → image.application.PlayerPolicy
  | _, _, _, _, _, _, .ret _ _ _, _, _, _, _ => FinDist.pure .wait
  | _, _, _, _, _, _, .sample (state := state) next, profile, player, history, view =>
      if view.application.done state.nodes.length then
        liftProfileIn image deadlineOf next profile.afterSample player history view
      else FinDist.pure .wait
  | _, _, _, _, _, _,
      .binding (name := name) (who := owner) (guard := guard) (tail := tail)
        (fresh := fresh) (state := state) _ next, profile, player, history, view =>
      if view.application.done state.nodes.length then
        liftProfileIn image deadlineOf next profile.afterCommit player history view
      else if player = owner then
        let site : SourceDecisionSite owner (.commit name owner guard tail) _ name _ guard :=
          .here guard tail
        site.bindingPolicy fresh state image (profile owner site) history view
      else FinDist.pure .wait
  | _, _, _, _, _, _,
      .publicChoice (name := name) (publicName := publicName) (who := owner)
        (guard := guard) (tail := tail) (fresh := fresh) (state := state) _ next,
        profile, player, history, view =>
      if view.application.done (state.nodes.length + 1) then
        liftProfileIn image deadlineOf next profile.afterCommit.afterReveal player history view
      else if player = owner then
        let site := PublicChoiceSite.atHead name publicName owner guard tail
        (site.imageController fresh state image
          (image.ownerReadout? owner (site.compiledGuard fresh state).choiceReads)
          (profile owner site.decision) (fun _ _ => false)).policy image.application history view
      else FinDist.pure .wait
  | _, _, _, _, _, _,
      .conditional (name := name) (publicName := publicName) (who := owner)
        (guard := guard) (tail := tail) (spec := spec)
        (fresh := fresh) (state := state) _ next, profile, player, history, view =>
      if view.application.done (state.nodes.length + 1) then
        liftProfileIn image deadlineOf next profile.afterCommit.afterReveal player history view
      else if player = owner then
        let site := ConditionalPublicationSite.atHead name publicName owner guard tail spec
        (site.imageController fresh state (site.sourceField fresh state)
          (deadlineOf (site.choice.publicationNode fresh state)) image
          (image.ownerReadout? owner (site.choice.compiledGuard fresh state).choiceReads)
          (profile owner site.choice.decision) (fun _ _ => false)).policy
            image.application history view
      else FinDist.pure .wait
  | _, _, _, _, _, _,
      .conditionalCopy (name := name) (publicName := publicName) (who := owner)
        (guard := guard) (tail := tail) (fresh := fresh) (state := state) spec _ next,
        profile, player, history, view =>
      if view.application.done (state.nodes.length + 1) then
        liftProfileIn image deadlineOf next profile.afterCommit.afterReveal player history view
      else if player = owner then
        let site := ConditionalPublicationSite.atHead name publicName owner guard tail spec
        (site.imageController fresh state (site.sourceField fresh state)
          (deadlineOf (site.choice.publicationNode fresh state)) image
          (image.ownerReadout? owner (site.choice.compiledGuard fresh state).choiceReads)
          (profile owner site.choice.decision) (fun _ _ => false)).policy
            image.application history view
      else FinDist.pure .wait

/-- Lift a source behavioral profile to source-ordered reference policies for
this plan's generated application. This constructs no client artifact and
selects no environment policy. -/
def liftProfile
    {Γ : VCtx P L} {pending : Finset VarId} {prog : VegasCore P L Γ}
    {accounted : CommitmentAccounting pending prog} {fresh : FreshBindings prog}
    {state : BuildState P L Γ} (plan : ApplicationPlan accounted fresh state)
    (deadlineOf : Nat → Nat) (profile : SourceBehavioralProfile prog) :
    P → (plan.image deadlineOf).application.PlayerPolicy :=
  plan.liftProfileIn (plan.image deadlineOf) deadlineOf profile

end Vegas.ApplicationPlan
