/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Compile.ApplicationImage
import Vegas.Compile.PublicChoiceExecution
import Vegas.Compile.PublicChoiceValidation

/-! # Public-choice application images generated from source occurrences

An adjacent source choice/reveal occurrence emits one executable public-choice
instruction. The correctness
statements connect actual pending-message inclusion to the source guard and its
two source steps; source environments remain proof data, not runtime state.
-/

noncomputable section

namespace Vegas

open EventGraph ToEventGraph Interaction GameTheory.Math.Probability

variable {P : Type} [DecidableEq P] {L : IExpr}

namespace PublicChoiceSite

/-- Executable instruction generated by an adjacent source choice/reveal pair. -/
def code {Γ : VCtx P L} {prog : VegasCore P L Γ}
    (site : PublicChoiceSite prog) (fresh : FreshBindings prog)
    (state : BuildState P L Γ) : PublicChoiceCode P L where
  endpoint := site.runtimeSite fresh state
  guard := site.compiledGuard fresh state
  choiceField := (compileCore prog fresh state).graph.nodeTarget
    (site.choiceNode fresh state)
  publicationField := (compileCore prog fresh state).graph.nodeTarget
    (site.publicationNode fresh state)

/-- At a ready generated instruction, canonical owner acceptance is equivalent
to the original source guard when the guard's dependencies are publicly
available and the public store agrees with the represented source store. -/
theorem code_resolves_iff_source_legal
    {Γ : VCtx P L} {prog : VegasCore P L Γ}
    (site : PublicChoiceSite prog) (fresh : FreshBindings prog)
    (state : BuildState P L Γ) (representedStore publicStore : Store L)
    (env : VEnv L site.context)
    (heligible : site.PubliclyValidatable fresh state)
    (hagrees : (site.siteState fresh state).Agrees representedStore env)
    (hpublicStore : ∀ ref,
      (compileCore prog fresh state).graph.fieldRefPublic ref →
        Store.getAs publicStore ref.field ref.ty =
          Store.getAs representedStore ref.field ref.ty)
    (done : Nat → Bool)
    (hready : (site.runtimeSite fresh state).ready done = true)
    (serial : Nat) (value : L.Val site.ty) :
    (site.code fresh state).endpoint.resolve? done
          ((site.code fresh state).guard.validate publicStore)
          ⟨(site.owner, serial), value⟩ = some value ↔
      evalGuard site.guard value ((env.toView site.owner).eraseEnv) = true := by
  apply site.canonical_request_resolves_iff_source_legal fresh state env done
    ((site.code fresh state).guard.validate publicStore) hready
  intro chosen
  rw [show (site.code fresh state).guard.validate publicStore chosen =
      site.validator fresh state publicStore chosen by rfl]
  rw [site.validator_source_of_publiclyValidatable fresh state representedStore
    publicStore env heligible hagrees hpublicStore chosen]

end PublicChoiceSite

namespace ApplicationImage

/-- A legal canonical source choice is accepted by actual pending-message
inclusion with the exact public memory, receipt, ledger, and message-knowledge
effects, and performs the certified adjacent source choice/reveal steps. -/
theorem include_source_choice
    {Γ : VCtx P L} {prog : VegasCore P L Γ}
    (image : ApplicationImage P L) (site : PublicChoiceSite prog)
    (fresh : FreshBindings prog) (state : BuildState P L Γ)
    (representedStore : Store L) (env : VEnv L site.context)
    (execution : image.application.State)
    (heligible : site.PubliclyValidatable fresh state)
    (hagrees : (site.siteState fresh state).Agrees representedStore env)
    (hpublicStore : ∀ ref,
      (compileCore prog fresh state).graph.fieldRefPublic ref →
        Store.getAs execution.application.memory.store ref.field ref.ty =
          Store.getAs representedStore ref.field ref.ty)
    (hready : (site.runtimeSite fresh state).ready
      execution.application.memory.done = true)
    (address serial : Nat)
    (hcode : image.lookup address = some (.publicChoice (site.code fresh state)))
    (value : L.Val site.ty)
    (hlookup : execution.pool.lookup (site.owner, serial) =
      some ⟨(site.owner, serial),
        .choice address ⟨site.ty, value⟩⟩)
    (hlegal : evalGuard site.guard value
      ((env.toView site.owner).eraseEnv) = true) :
    let code := site.code fresh state
    let next := image.application.includePending execution (site.owner, serial)
    next.application = execution.application.publish code value ∧
      next.receipts = execution.receipts ++ [((site.owner, serial), true)] ∧
      next.pool.ledger = execution.pool.ledger ++
        [⟨(site.owner, serial), .choice address ⟨site.ty, value⟩⟩] ∧
      next.pool.sent = execution.pool.sent ∧
      next.pool.inbox = execution.pool.inbox ∧
      SmallStep.Star
        ⟨site.context, env,
          .commit site.choiceName site.owner site.guard site.decision.continuation⟩
        ⟨(site.publicName, .pub site.ty) ::
            (site.choiceName, .sealed site.owner site.ty) :: site.context,
          (env.cons value).cons value, site.tail⟩ := by
  have hresolve := (site.code_resolves_iff_source_legal fresh state representedStore
    execution.application.memory.store env heligible hagrees hpublicStore
    execution.application.memory.done hready serial value).2 hlegal
  have hincluded := image.include_choice execution address (site.code fresh state)
    hcode (site.owner, serial) value hlookup hresolve
  have hsteps := site.completePublication_source_steps env value hlegal
  exact ⟨hincluded.1, hincluded.2.1, hincluded.2.2.1, hincluded.2.2.2.1,
    hincluded.2.2.2.2, hsteps⟩

end ApplicationImage

end Vegas

/-- info: 'Vegas.ApplicationImage.include_source_choice' depends on axioms: [propext,
Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Vegas.ApplicationImage.include_source_choice
