/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Interaction.SealedProgram

/-! # Native actions for a sealed-message application

Actions reuse the message pool and application handler directly. Raw submission
admits every payload, including cleartext and openings not generated by the
honest controller. Private registration is separate from submission. Delivery
only changes the recipient's inbox; inclusion publishes a preexisting message.

These are possible operational actions, not authenticated capabilities or a
strategy interface: raw `owner` and `sender` arguments are only control labels.
A principal-scoped policy interface must assign their controls and restrict
each policy's input to its observation. There is no automatic clock, fairness,
or settlement event.
-/

namespace Interaction.SealedProgram

universe uPrincipal uValue

variable {Principal : Type uPrincipal} {Value : Type uValue}

inductive Action (Principal : Type uPrincipal) (Value : Type uValue) where
  | register (owner : Principal) (slot : Nat) (value : Value)
  | submit (sender : Principal) (payload : Payload Principal Value)
  | deliver (observer : Principal) (id : MessageId Principal)
  | include (id : MessageId Principal)

/-- One native operational action, without selecting an actor or policy. -/
def step [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value) :
    Action Principal Value → State Principal Value
  | .register owner slot value =>
      { state with service := (state.service.sealValue owner slot value).state }
  | .submit sender payload => { state with pool := (state.pool.submit sender payload).2 }
  | .deliver observer id => { state with pool := (state.pool.deliver observer id).state }
  | .include id => includePending program state id

/-- Execute a supplied finite action sequence in the native runtime. -/
def run [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value)
    (actions : List (Action Principal Value)) : State Principal Value :=
  actions.foldl (step program) state

@[simp] theorem run_nil [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value) :
    run program state [] = state := rfl

@[simp] theorem run_cons [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value)
    (action : Action Principal Value) (rest : List (Action Principal Value)) :
    run program state (action :: rest) = run program (step program state action) rest := rfl

theorem run_append [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value)
    (first second : List (Action Principal Value)) :
    run program state (first ++ second) = run program (run program state first) second := by
  exact List.foldl_append

/-- The compiled commitment helper is two actual native actions, not a
separate execution rule. -/
theorem submitCommit_eq_run [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value)
    (owner : Principal) (node : Nat) (value : Value) :
    (submitCommit state owner node value).2 =
      run program state [.register owner node value,
        .submit owner (.commitment node (owner, node))] := rfl

/-- A generated opening is submitted by the same raw native operation that
also admits malformed and prematurely disclosed payloads. -/
theorem submitOpening?_eq_step [DecidableEq Principal] [DecidableEq Value]
    (program : SealedProgram Principal) (state : State Principal Value)
    (owner : Principal) (node : Nat) (value : Value)
    (payload : Payload Principal Value)
    (hrequest : openingRequest? program state.events owner node value = some payload) :
    (submitOpening? program state owner node value).map Prod.snd =
      some (step program state (.submit owner payload)) := by
  simp [submitOpening?, hrequest, step]

end Interaction.SealedProgram
